import { pgTable, text, timestamp, jsonb, boolean } from "drizzle-orm/pg-core";

export const protocols = pgTable("protocols", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  ticker: text("ticker"),
  icon: text("icon"),
  aliases: jsonb("aliases").notNull().$type<string[]>(),
  category: text("category").notNull(),
  chain: text("chain").notNull(),
  settlementLayer: text("settlement_layer"),
  kind: text("kind").notNull(),
  description: text("description").notNull(),
  launchDate: text("launch_date").notNull(),
  githubRepo: text("github_repo"),
  coingeckoId: text("coingecko_id"),
  defillamaSlug: jsonb("defillama_slug").$type<string[] | null>(),
  defillamaUseFastEndpoint: boolean("defillama_use_fast_endpoint").notNull(),
  whaleTokenAddress: text("whale_token_address"),
  // LunarCrush ticker symbol apps/api/ingestion/social.py polls (e.g. "AAVE").
  lunarcrushSymbol: text("lunarcrush_symbol"),
  sentimentSubreddits: jsonb("sentiment_subreddits").$type<string[] | null>(),
  snapshotSpace: jsonb("snapshot_space").$type<string[] | null>(),
  typedSignalCatalog: jsonb("typed_signal_catalog").$type<Record<string, string> | null>(),
  links: jsonb("links").notNull().$type<Record<string, unknown>>(),
  market: jsonb("market").$type<Record<string, unknown> | null>(),
  assessment: jsonb("assessment").notNull().$type<Record<string, unknown>>(),
  assessmentHistory: jsonb("assessment_history").notNull().$type<unknown[]>(),
  signals: jsonb("signals").notNull().$type<Record<string, unknown>>(),
  risk: jsonb("risk").notNull().$type<unknown[]>(),
  contracts: jsonb("contracts").notNull().$type<unknown[]>(),
  incidents: jsonb("incidents").notNull().$type<unknown[]>(),
  dependencies: jsonb("dependencies").notNull().$type<unknown[]>(),
  askSuggestions: jsonb("ask_suggestions").notNull().$type<string[]>(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull(),
});
