import { pgTable, text, doublePrecision, jsonb, boolean, timestamp } from "drizzle-orm/pg-core";

export const strategies = pgTable("strategies", {
  protocolId: text("protocol_id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  adapter: text("adapter").notNull(),
  strategyAddress: text("strategy_address").notNull(),
  stratName: text("strat_name").notNull(),
  native: text("native").notNull(),
  rewards: jsonb("rewards").notNull().$type<string[]>(),
  harvestOnDeposit: boolean("harvest_on_deposit").notNull(),
  asset: text("asset").notNull(),
  want: text("want").notNull(),
  allocated: doublePrecision("allocated").notNull(),
  targetWeight: doublePrecision("target_weight").notNull(),
  actualWeight: doublePrecision("actual_weight").notNull(),
  score: doublePrecision("score").notNull(),
  apy: doublePrecision("apy").notNull(),
  lastRebalance: timestamp("last_rebalance", { mode: "date" }).notNull(),
  paused: boolean("paused").notNull(),
  retired: boolean("retired").notNull(),
  lastHarvest: timestamp("last_harvest", { mode: "date" }).notNull(),
  harvestable: boolean("harvestable").notNull(),
  maxWithdraw: doublePrecision("max_withdraw").notNull(),
  maxDeposit: doublePrecision("max_deposit"),
  depositFee: doublePrecision("deposit_fee").notNull(),
  withdrawFee: doublePrecision("withdraw_fee").notNull(),
});
