// ─────────────────────────────────────────────────────────────
// Reads apps/contracts/data/<chainId>/token.json (written by
// SeedTokens.s.sol) and emits a single typed lib/testTokens.ts the faucet
// UI imports instead of hand-copying the token list after every deploy.
// Mirrors sync-contracts.ts's shape/conventions.
// Run with: pnpm sync-test-tokens (see deploy.sh, which runs it automatically)
// ─────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.join(here, "../../contracts");
const dataDir = path.join(contractsDir, "data");
const outFile = path.join(here, "../lib/testTokens.ts");

interface TestToken {
  address: string;
  symbol: string;
  name: string;
  decimals: number;
  kind: string;
  logoURI: string;
}

type TestTokensByChain = Record<string, TestToken[]>;

function sync(): TestTokensByChain {
  const result: TestTokensByChain = {};

  if (!fs.existsSync(dataDir)) {
    return result;
  }

  for (const chainId of fs.readdirSync(dataDir)) {
    const manifestPath = path.join(dataDir, chainId, "token.json");
    if (!fs.existsSync(manifestPath)) continue;

    const raw: Record<string, unknown>[] = JSON.parse(
      fs.readFileSync(manifestPath, "utf8"),
    );

    // token.json's shape has drifted across chains/eras (some entries
    // predate the "token"/"kind" fields SeedTokens.s.sol writes today) -
    // skip anything without a real address rather than emitting a token
    // the faucet could never actually send.
    const tokens: TestToken[] = [];
    let skipped = 0;
    for (const e of raw) {
      if (typeof e.token !== "string" || !e.token) {
        skipped++;
        continue;
      }
      tokens.push({
        address: e.token,
        symbol: String(e.symbol ?? ""),
        name: String(e.name ?? ""),
        decimals: Number(e.decimals ?? 18),
        kind: String(e.kind ?? "Single"),
        logoURI: String(e.logoURI ?? ""),
      });
    }
    if (skipped > 0) {
      console.log(`  chain ${chainId}: skipped ${skipped} entr(ies) missing a token address`);
    }
    result[chainId] = tokens;
  }

  return result;
}

function writeOutput(tokens: TestTokensByChain) {
  // No `as const` - with 1000+ entries accumulated across dev/test/prod
  // chains, inferring a full literal type per field made `tsc` grind to a
  // halt. An explicit interface is all any consumer needs.
  const banner = `// AUTO-GENERATED by apps/web/scripts/sync-test-tokens.ts - do not edit by hand.\n// Re-run \`pnpm sync-test-tokens\` (or \`deploy.sh\`) after deploying/changing tokens.\n\n`;
  const iface = `export interface TestToken {\n  address: string;\n  symbol: string;\n  name: string;\n  decimals: number;\n  kind: string;\n  logoURI: string;\n}\n\n`;
  const body = `export const testTokens: Record<string, TestToken[]> = ${JSON.stringify(tokens, null, 2)};\n`;
  fs.writeFileSync(outFile, banner + iface + body);

  const chainCount = Object.keys(tokens).length;
  const tokenCount = Object.values(tokens).reduce((n, t) => n + t.length, 0);
  console.log(
    `wrote ${outFile} (${tokenCount} token(s) across ${chainCount} chain(s))`,
  );
}

writeOutput(sync());
