// ─────────────────────────────────────────────────────────────
// Verifies which real CoinGecko coin each testTokens.ts entry impersonates
// and writes lib/tokenPriceIds.ts (address -> coingecko id), so runtime
// pricing (app/api/token-prices/route.ts) never has to guess by symbol.
//
// Symbol alone is NOT enough - "dai" matches 28 CoinGecko coins, "wsteth"
// matches 15. Every test token's logoURI is a real CoinGecko image URL
// (embeds that coin's numeric image id), so a candidate is only accepted
// when ITS OWN CoinGecko image id matches ours exactly - i.e. the two are
// provably the same coin, not just same-ticker.
//
// Run with: pnpm sync-token-prices (after sync-test-tokens, since this
// reads lib/testTokens.ts)
// ─────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { testTokens, type TestToken } from "../lib/testTokens";

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, "../lib/tokenPriceIds.ts");

const COINGECKO_API = "https://api.coingecko.com/api/v3";
const MARKETS_CHUNK = 250;

interface CoinListEntry {
  id: string;
  symbol: string;
  name: string;
}

interface CoinMarket {
  id: string;
  image: string;
}

function imageId(url: string): string | null {
  return url.match(/\/coins\/images\/(\d+)\//)?.[1] ?? null;
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.json() as Promise<T>;
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function fetchMarkets(ids: string[]): Promise<CoinMarket[]> {
  const results = await Promise.all(
    chunk(ids, MARKETS_CHUNK).map((c) =>
      fetchJson<CoinMarket[]>(`${COINGECKO_API}/coins/markets?vs_currency=usd&ids=${c.join(",")}&per_page=${MARKETS_CHUNK}&page=1`),
    ),
  );
  return results.flat();
}

async function resolveChain(chainId: string, tokens: TestToken[], coinList: CoinListEntry[]): Promise<Record<string, string>> {
  const bySymbol = new Map<string, CoinListEntry[]>();
  for (const c of coinList) {
    const s = c.symbol.toLowerCase();
    if (!bySymbol.has(s)) bySymbol.set(s, []);
    bySymbol.get(s)!.push(c);
  }

  const candidateIds = new Set<string>();
  for (const t of tokens) {
    for (const c of bySymbol.get(t.symbol.toLowerCase()) ?? []) candidateIds.add(c.id);
  }

  const markets = await fetchMarkets([...candidateIds]);
  const marketById = new Map(markets.map((m) => [m.id, m]));

  const resolved: Record<string, string> = {};
  const unresolved: string[] = [];

  for (const t of tokens) {
    const ourImg = imageId(t.logoURI);
    const candidates = bySymbol.get(t.symbol.toLowerCase()) ?? [];
    const matches = candidates
      .map((c) => marketById.get(c.id))
      .filter((m): m is CoinMarket => m != null && imageId(m.image) === ourImg);

    if (matches.length === 1) {
      resolved[t.address.toLowerCase()] = matches[0]!.id;
    } else {
      unresolved.push(`${t.symbol} (${t.name}) - ${matches.length === 0 ? "no verified match" : `${matches.length} ambiguous matches`}`);
    }
  }

  if (unresolved.length > 0) {
    console.log(`  chain ${chainId}: ${unresolved.length} token(s) left unpriced -`);
    unresolved.forEach((u) => console.log(`    - ${u}`));
  }

  return resolved;
}

async function main() {
  console.log("Fetching CoinGecko's full coin list...");
  const coinList = await fetchJson<CoinListEntry[]>(`${COINGECKO_API}/coins/list`);

  const byChain: Record<string, Record<string, string>> = {};
  for (const [chainId, tokens] of Object.entries(testTokens)) {
    if (tokens.length === 0) continue;
    console.log(`Resolving ${tokens.length} token(s) on chain ${chainId}...`);
    byChain[chainId] = await resolveChain(chainId, tokens, coinList);
  }

  const banner = `// AUTO-GENERATED by apps/web/scripts/sync-token-prices.ts - do not edit by hand.\n// Re-run \`pnpm sync-token-prices\` after testTokens.ts changes.\n//\n// address (lowercase) -> the CoinGecko coin id it's verified to impersonate\n// (matched on symbol AND a byte-identical CoinGecko image id - see the\n// script header for why symbol alone isn't trustworthy). A token missing\n// from its chain's map has no verified match and is priced as unknown.\n\n`;
  const body = `export const tokenPriceIds: Record<string, Record<string, string>> = ${JSON.stringify(byChain, null, 2)};\n`;
  fs.writeFileSync(outFile, banner + body);

  const total = Object.values(byChain).reduce((n, m) => n + Object.keys(m).length, 0);
  console.log(`wrote ${outFile} (${total} token(s) resolved)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
