import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.join(here, "../../contracts");
const dataDir = path.join(contractsDir, "data");
const outDir = path.join(contractsDir, "out");
const outFile = path.join(here, "../lib/deployedContracts.ts");

type DeployedContracts = Record<
  string,
  Record<string, { address: string; abi: unknown[] }>
>;

function artifactAbi(sourceContractName: string): unknown[] | null {
  const artifactPath = path.join(
    outDir,
    `${sourceContractName}.sol`,
    `${sourceContractName}.json`,
  );
  if (!fs.existsSync(artifactPath)) return null;
  return JSON.parse(fs.readFileSync(artifactPath, "utf8")).abi;
}

function loadAbi(registeredName: string): unknown[] {
  const direct = artifactAbi(registeredName);
  if (direct) return direct;

  const sourceContractName = registeredName.startsWith("Vault_")
    ? "VigilVault"
    : "MockStrategyAdapter";
  const fallback = artifactAbi(sourceContractName);
  if (fallback) return fallback;

  throw new Error(
    `No build artifact for "${registeredName}" (tried "${registeredName}" and "${sourceContractName}") - run \`forge build\` in apps/contracts first.`,
  );
}

function sync(): DeployedContracts {
  const result: DeployedContracts = {};

  if (!fs.existsSync(dataDir)) {
    return result;
  }

  for (const chainId of fs.readdirSync(dataDir)) {
    const manifestPath = path.join(dataDir, chainId, "deployedContracts.json");
    if (!fs.existsSync(manifestPath)) continue;

    const addresses: Record<string, string> = JSON.parse(
      fs.readFileSync(manifestPath, "utf8"),
    );
    result[chainId] = {};
    for (const [name, address] of Object.entries(addresses)) {
      result[chainId][name] = { address, abi: loadAbi(name) };
    }
  }

  return result;
}

function writeOutput(contracts: DeployedContracts) {
  const banner = `// AUTO-GENERATED by apps/web/scripts/sync-contracts.ts - do not edit by hand.\n// Re-run \`pnpm sync-contracts\` (or \`deploy.sh\`) after deploying/changing contracts.\n\n`;
  const iface = `export interface DeployedContract {\n  address: string;\n  abi: unknown[];\n}\n\n`;
  const body = `export const deployedContracts: Record<string, Record<string, DeployedContract>> = ${JSON.stringify(contracts, null, 2)};\n`;
  fs.writeFileSync(outFile, banner + iface + body);

  const chainCount = Object.keys(contracts).length;
  const contractCount = Object.values(contracts).reduce(
    (n, c) => n + Object.keys(c).length,
    0,
  );
  console.log(
    `wrote ${outFile} (${contractCount} contract(s) across ${chainCount} chain(s))`,
  );
}

writeOutput(sync());
