// ─────────────────────────────────────────────────────────────
// Reads apps/contracts/data/<chainId>/deployedContracts.json (written by
// each Foundry deploy script via script/lib/DeployRegistrar.sol) and the
// matching ABI from apps/contracts/out/<Name>.sol/<Name>.json, then emits
// a single typed lib/deployedContracts.ts the frontend imports instead of
// hand-copying addresses/ABIs after every deploy.
// Run with: pnpm sync-contracts (see deploy.sh, which runs it automatically)
// ─────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.join(here, "../../contracts");
const dataDir = path.join(contractsDir, "data");
const outDir = path.join(contractsDir, "out");
const outFile = path.join(here, "../lib/deployedContracts.ts");

type DeployedContracts = Record<
  string,
  Record<string, { address: string; abi: unknown[] }>
>;

function loadAbi(contractName: string): unknown[] {
  const artifactPath = path.join(
    outDir,
    `${contractName}.sol`,
    `${contractName}.json`,
  );
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `No build artifact for "${contractName}" at ${artifactPath} - run \`forge build\` in apps/contracts first.`,
    );
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

function sync(): DeployedContracts {
  const result: DeployedContracts = {};

  if (!fs.existsSync(dataDir)) {
    return result;
  }

  for (const chainId of fs.readdirSync(dataDir)) {
    const manifestPath = path.join(dataDir, chainId, "deployedContracts.json");
    if (!fs.existsSync(manifestPath)) continue;

    const addresses: Record<string, string> = JSON.parse(
      fs.readFileSync(manifestPath, "utf8"),
    );
    result[chainId] = {};
    for (const [name, address] of Object.entries(addresses)) {
      result[chainId][name] = { address, abi: loadAbi(name) };
    }
  }

  return result;
}

function writeOutput(contracts: DeployedContracts) {
  const banner = `// AUTO-GENERATED by apps/web/scripts/sync-contracts.ts - do not edit by hand.\n// Re-run \`pnpm sync-contracts\` (or \`deploy.sh\`) after deploying/changing contracts.\n\n`;
  const body = `export const deployedContracts = ${JSON.stringify(contracts, null, 2)} as const;\n`;
  fs.writeFileSync(outFile, banner + body);

  const chainCount = Object.keys(contracts).length;
  const contractCount = Object.values(contracts).reduce(
    (n, c) => n + Object.keys(c).length,
    0,
  );
  console.log(
    `wrote ${outFile} (${contractCount} contract(s) across ${chainCount} chain(s))`,
  );
}

writeOutput(sync());
